#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git ls-files julia/Manifest.toml &> /dev/null; then
  cd julia
  .nix/julia2nix/julia2nix -o .nix
  git add .nix/default.nix .nix/common.nix .nix/packages.nix .nix/fetchgit
  cd ..
fi
