#!/bin/sh

if git diff --cached --name-only | grep -q 'julia/Manifest.toml'; then
  echo "pre-commit: Modified 'julia/Manifest.toml'."
  echo "pre-commit: Rebuilding nix files ... "
  cd julia
  .nix/julia2nix/julia2nix -o .nix
  git add .nix/default.nix .nix/common.nix .nix/packages.nix .nix/fetchgit
  cd ..
  echo "pre-commit: ... done."
fi
